### ISSUE TITLE
No class def error

### ISSUE THREAD

**Issue by scruffyfox** [tom-bell/Bearing#12] opened 2015-01-16 15:14 UTC
Apparently LocationClient has now been removed and is causing a crash when trying to fetch a users location

```
 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/location/LocationClient;
            at net.atomcode.bearing.location.provider.GMSLocationProvider.create(GMSLocationProvider.java:48)
            at net.atomcode.bearing.location.LocationTask.<init>(LocationTask.java:50)
            at net.atomcode.bearing.location.CurrentLocationTask.<init>(CurrentLocationTask.java:13)
            at net.atomcode.bearing.Bearing.locate(Bearing.java:151)
            at MainActivity.onCreate(MainActivity.java:80)
            at android.app.Activity.performCreate(Activity.java:5231)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2169)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2271)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1205)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5146)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.location.LocationClient" on path: DexPathList[[zip file "/data/app/help.com.cube.emergencyhelp-1.apk"],nativeLibraryDirectories=[/data/app-lib/help.com.cube.emergencyhelp-1, /vendor/lib, /system/lib]]
            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
            at net.atomcode.bearing.location.provider.GMSLocationProvider.create(GMSLocationProvider.java:48)
            at net.atomcode.bearing.location.LocationTask.<init>(LocationTask.java:50)
            at net.atomcode.bearing.location.CurrentLocationTask.<init>(CurrentLocationTask.java:13)
            at net.atomcode.bearing.Bearing.locate(Bearing.java:151)
            at MainActivity.onCreate(MainActivity.java:80)
            at android.app.Activity.performCreate(Activity.java:5231)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2169)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2271)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1205)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5146)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
    Suppressed: java.lang.ClassNotFoundException: com.google.android.gms.location.LocationClient
            at java.lang.Class.classForName(Native Method)
            at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
            at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
            ... 18 more
     Caused by: java.lang.NoClassDefFoundError: Class "Lcom/google/android/gms/location/LocationClient;" not found
            ... 22 more
```

**Comment by tom-bell** [comment] 2015-01-16 16:34
Duplicate of #11 Fix inbound.

**Closed by tom-bell** 2015-01-16 16:34 UTC

**Comment by scruffyfox** [comment] 2015-01-16 16:35
:+1:
